### ISSUE TITLE
vine_ best_ fit.py has problems with BSF implementation

### ISSUE THREAD

**Issue by LordFoxFairy** [gsoosk/GraphViNE#1]
.

**Comment by TheFoxFairy** [comment]
你好，我经过调试你的代码，终于修复了这个bug，如下


def embed_request_in_cluster(request_graph, physical_graph, center_node, max_visit, beta=10, verbose=False,
                             check_verbose=False, embedding_verbose=False):
    r"""
    Try to embed a request in some adjacent nodes of a center selected from a cluster 
    It uses BFS to traverse graph and in each itteration it selected best nodes in a depth

    Returns: embedding was successfull or not
    """
    beta = 1000
    max_depth = beta
    q = request_graph
    # sorted_request_nodes = sorted(q.nodes(data=True), key=lambda t: t[1]['CPU'] + (
    #     (t[1]['GPU']+t[1]['Memory']) if 'GPU' in t[1] else 0), reverse=True)  # descending
    sorted_request_nodes = sorted(q.nodes(data=True), key=lambda t: t[0])

    max_visit_in_every_depth = int(np.power(max_visit, 1 / max_depth))
    result = {}

    depth = 0
    visited = physical_graph.number_of_nodes() * [False]
    queue = [(center_node, depth)]
    visited[center_node] = True
    visited[center_node] = True

    j = 0
    i = sorted_request_nodes[j][0]
    node_embedded = False
    while queue:
        (current_node, depth) = queue.pop(0)
        # print(current_node)
        if depth > max_depth:
            break
        if can_embed(current_node, i, q, physical_graph, verbose=check_verbose):
            try:
                embed_to_physical(current_node, i, q,
                                  physical_graph, verbose=embedding_verbose)
                node_embedded = True
                j = j + 1
                if j >= len(sorted_request_nodes):
                    # print(request_graph.edges.data('Embedded'))
                    # print(request_graph.nodes.data('Embedded'))
                    return True
                i = sorted_request_nodes[j][0]
                # print(i)
            except nx.NetworkXNoPath:  # In a rare case of having no path after embed some bandwidths
                free_embedded_request_node(physical_graph, q, i)

        if depth == max_depth:
            continue

        # node_edges = physical_graph.edges(center_node, data=True)
        # node_edges = node_edges if len(node_edges) <= max_visit else node_edges[:max_visit_in_every_depth]

        node_edges = physical_graph.edges(current_node, data=True)

        for edge in node_edges:
            dst = edge[1]
            if not visited[dst]:
                queue.append((dst, depth + 1))
                visited[dst] = True

    return False
